# Generated by Django 5.1.6 on 2025-02-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("ledger_lokasi", "Ledger per Lokasi"),
                            ("tagihan_pekerjaan", "Tagihan Pekerjaan (BAPP)"),
                            ("pembayaran_pekerjaan", "Pembayaran Pekerjaan (BAPP)"),
                            ("pembelian_sparepart", "Pembelian Sparepart"),
                            ("penggantian_kas_kantor", "Penggantian Kas Kantor"),
                            (
                                "biaya_pengeluaran_proyek",
                                "Biaya Pengeluaran per Proyek",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        choices=[
                            ("ttu", "TTU (Tunggal Tunggu Unggul)"),
                            ("asn", "ASN (Alam Subur Nusantara)"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(blank=True, null=True, upload_to="uploads/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
