# Generated by Django 5.1.6 on 2025-02-25 08:55

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="uploads/",
                validators=[documents.models.validate_file_extension],
            ),
        ),
    ]
