# Generated by Django 5.1.6 on 2025-02-26 18:39

import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(upload_to='uploads/supporting_docs/', validators=[documents.models.validate_file_extension])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_docs', to='documents.document')),
            ],
        ),
    ]
