# Generated by Django 5.1.6 on 2025-03-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_alter_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('belum_disetujui', 'Belum Disetujui'), ('disetujui', 'Disetujui'), ('rejected', 'Ditolak')], default='draft', max_length=20),
        ),
    ]
