# Generated by Django 5.1.6 on 2025-03-04 17:04

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_document_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_code',
            field=models.CharField(blank=True, default=documents.models.generate_document_code, max_length=20, null=True),
        ),
    ]
