# Generated by Django 5.1.6 on 2025-03-04 17:11

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_fix_document_code_uniqueness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_code',
            field=models.CharField(default=documents.models.generate_document_code, max_length=20, unique=True),
        ),
    ]
