# Generated by Django 5.1.6 on 2025-03-25 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_alter_document_document_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedSubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('main_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='ParsedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=255)),
                ('sub_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.parsedsubsection')),
            ],
        ),
    ]
