# Generated by Django 5.1.6 on 2025-03-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_parsedsubsection_parseditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='parsed_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
