# Generated by Django 5.1.6 on 2025-03-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_document_parsed_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsedsubsection',
            name='main_document',
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('ledger_lokasi', 'Ledger per Lokasi'), ('tagihan_pekerjaan', 'Tagihan Pekerjaan (BAPP)'), ('pembayaran_pekerjaan', 'Pembayaran Pekerjaan (BAPP)'), ('pembelian_sparepart', 'Pembelian Sparepart'), ('penggantian_kas_kantor', 'Penggantian Kas Kantor'), ('biaya_pengeluaran_proyek', 'Biaya Pengeluaran Proyek')], max_length=50),
        ),
        migrations.DeleteModel(
            name='ParsedItem',
        ),
        migrations.DeleteModel(
            name='ParsedSubSection',
        ),
    ]
