# Generated by Django 5.1.6 on 2025-03-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_remove_parsedsubsection_main_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportingdocument',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='row_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
