# Generated by Django 5.1.6 on 2025-03-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_supportingdocument_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportingdocument',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
