# Generated by Django 5.1.6 on 2025-03-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_alter_supportingdocument_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportingdocument',
            name='section_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
