# Generated by Django 5.1.6 on 2025-04-21 07:04

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_supportingdocument_approved_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentStateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(max_length=30)),
                ('to_state', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=django_fsm.FSMField(default='draft', max_length=50, protected=True),
        ),
        migrations.AlterField(
            model_name='supportingdocument',
            name='status',
            field=django_fsm.FSMField(default='draft', max_length=50, protected=True),
        ),
        migrations.AddConstraint(
            model_name='supportingdocument',
            constraint=models.UniqueConstraint(fields=('main_document', 'section_index', 'row_index', 'file'), name='unique_supporting_doc_per_row'),
        ),
        migrations.AddField(
            model_name='documentstatelog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentstatelog',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
    ]
