# Generated by Django 5.1.6 on 2025-04-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_documentstatelog_alter_document_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentstatelog',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='documentstatelog',
            name='document',
        ),
        migrations.RemoveConstraint(
            model_name='supportingdocument',
            name='unique_supporting_doc_per_row',
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('belum_disetujui', 'Belum Disetujui'), ('disetujui', 'Disetujui'), ('rejected', 'Ditolak')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='supportingdocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('disetujui', 'Disetujui'), ('rejected', 'Ditolak')], default='draft', max_length=20),
        ),
        migrations.DeleteModel(
            name='DocumentStateLog',
        ),
    ]
