# Generated by Django 5.1.6 on 2025-04-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0024_remove_documentstatelog_actor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='reject_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
