# Generated by Django 5.1.6 on 2025-06-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0026_document_paid_at_document_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('belum_disetujui', 'Belum Disetujui'), ('disetujui', 'Disetujui'), ('rejected', 'Ditolak'), ('sudah_dibayar', 'Sudah Dibayar')], default='draft', max_length=20),
        ),
    ]
