# Generated by Django 5.1.6 on 2025-06-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0027_document_archived_document_archived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='finished_draft_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
