# Generated by Django 5.1.6 on 2025-06-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0028_document_finished_draft_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='revision_no',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='document',
            name='sequence_no',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='company',
            field=models.CharField(choices=[('ttu', 'TTU (Tunggal Tunggu Unggul)'), ('asn', 'ASN (Alam Subur Nusantara)'), ('ols', 'OLS'), ('olm', 'OLM')], max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_code',
            field=models.CharField(editable=False, max_length=32, unique=True),
        ),
    ]
