# Generated by Django 5.1.6 on 2025-06-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0029_document_revision_no_document_sequence_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='company',
            field=models.CharField(choices=[('ttu', 'TTU'), ('asn', 'ASN'), ('ols', 'OLS'), ('olm', 'OLM')], max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_code',
            field=models.CharField(editable=False, max_length=40, unique=True),
        ),
    ]
