# Generated by Django 5.1.6 on 2025-06-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0030_alter_document_company_alter_document_document_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='report_file',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('ledger_lokasi', 'Ledger per Lokasi'), ('tagihan_pekerjaan', 'Tagihan Pekerjaan (BAPP)'), ('pembayaran_pekerjaan', 'Pembayaran Pekerjaan'), ('pembelian_sparepart', 'Pembelian Sparepart'), ('penggantian_kas_kantor', 'Penggantian Kas Kantor'), ('biaya_pengeluaran_proyek', 'Biaya Pengeluaran Proyek')], max_length=50),
        ),
    ]
