# Generated by Django 5.1.6 on 2025-06-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0031_document_report_file_alter_document_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
