# Generated by Django 5.1.6 on 2025-06-08 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0032_alter_document_report_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='report_file',
        ),
    ]
