# Generated by Django 5.1.6 on 2025-06-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0034_alter_document_company_alter_document_doc_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='company',
            field=models.CharField(choices=[('ttu', 'TTU'), ('asn', 'ASN'), ('ols', 'OLS'), ('olm', 'OLM')], max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('ledger_lokasi', 'Ledger per Lokasi'), ('tagihan_pekerjaan', 'Tagihan Pekerjaan (BAPP)'), ('pembayaran_pekerjaan', 'Pembayaran Pekerjaan'), ('pembelian_sparepart', 'Pembelian Sparepart'), ('penggantian_kas_kantor', 'Penggantian Kas Kantor'), ('biaya_pengeluaran_proyek', 'Biaya Pengeluaran Proyek')], max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_code',
            field=models.CharField(editable=False, max_length=40, unique=True),
        ),
    ]
