# Generated by Django 5.1.6 on 2025-06-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0035_alter_document_company_alter_document_doc_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportingdocument',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='supportingdocument',
            name='row_index',
        ),
        migrations.RemoveField(
            model_name='supportingdocument',
            name='section_index',
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='item_ref_code',
            field=models.CharField(db_index=True, default='DEFAULT_REF', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='supporting_doc_sequence',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
