# Generated by Django 5.1.6 on 2025-06-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0036_remove_supportingdocument_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportingdocument',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='row_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='section_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
