# Generated by Django 5.1.6 on 2025-06-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0038_remove_supportingdocument_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportingdocument',
            name='item_ref_code',
        ),
        migrations.RemoveField(
            model_name='supportingdocument',
            name='supporting_doc_sequence',
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='row_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='section_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('ledger_lokasi', 'Ledger per Lokasi'), ('tagihan_pekerjaan', 'Tagihan Pekerjaan (BAPP)'), ('pembayaran_pekerjaan', 'Pembayaran Pekerjaan (BAPP)'), ('pembelian_sparepart', 'Pembelian Sparepart'), ('penggantian_kas_kantor', 'Penggantian Kas Kantor'), ('biaya_pengeluaran_proyek', 'Biaya Pengeluaran Proyek')], max_length=50),
        ),
    ]
