# Generated by Django 5.1.6 on 2025-06-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0039_remove_supportingdocument_item_ref_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportingdocument',
            name='item_ref_code',
            field=models.CharField(db_index=True, default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='supporting_doc_sequence',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
