# Generated by Django 5.1.6 on 2025-06-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0040_supportingdocument_item_ref_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportingdocument',
            name='full_ref_code',
            field=models.CharField(default='', editable=False, max_length=14, unique=True),
            preserve_default=False,
        ),
    ]
