# Generated by Django 5.1.6 on 2025-06-16 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0041_supportingdocument_full_ref_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportingdocument',
            old_name='full_ref_code',
            new_name='identifier',
        ),
    ]
