# Generated by Django 5.1.6 on 2025-07-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0045_alter_supportingdocument_options_usersettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='theme_mode',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10),
        ),
    ]
