# Generated by Django 5.1.6 on 2025-08-04 05:01

import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0046_usersettings_theme_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_index', models.PositiveIntegerField()),
                ('item_index', models.PositiveIntegerField()),
                ('identifier', models.CharField(editable=False, max_length=50, unique=True)),
                ('file', models.FileField(upload_to='uploads/payment_proofs/', validators=[documents.models.validate_file_extension])),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('main_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to='documents.document')),
            ],
            options={
                'unique_together': {('main_document', 'section_index', 'item_index')},
            },
        ),
    ]
