# Generated by Django 5.2.5 on 2025-10-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0047_paymentproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportingdocument',
            name='ai_auto_attached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='ai_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='ai_low_confidence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='doc_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='previews/supporting_docs/'),
        ),
    ]
