# Generated by Django 5.2.5 on 2026-01-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0048_supportingdocument_ai_auto_attached_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
