# Generated by Django 5.2.5 on 2026-01-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0049_usersettings_whatsapp_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentproof',
            options={'ordering': ['payment_proof_sequence', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='paymentproof',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='paymentproof',
            name='payment_proof_sequence',
            field=models.PositiveSmallIntegerField(default=1, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='paymentproof',
            unique_together={('main_document', 'section_index', 'item_index', 'payment_proof_sequence')},
        ),
    ]
